name: Documentation generation & update

on:
  push:
    tags:
      - '*'
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
# Cancel previous runs on this reference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  generate:
    name: Generate the documentation
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install APT dependencies
        run: |
          sudo apt-get update
          sudo apt-get install graphviz
      - name: Install Python dependencies
        run: |
          pip install -U pip
          pip install .[doc]
      - name: Generating automatic resources
        run: (cd doc && make gen_resources)
      - name: Generate the documentation
        run: (cd doc && make html)
      - name: Upload documentation bundle
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: doc/build/html/

  deploy:
    name: Deploy the documentation on Github pages
    runs-on: ubuntu-latest
    needs: generate
    if: github.event_name == 'push'  && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Download documentation bundle
        uses: actions/download-artifact@v4
      - name: Deploy documentation on pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documentation/
