name: Fast checks

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  pull_request:
# Cancel previous runs on this reference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
    - run: pip install flake8 flake8-pyproject
    - name: Flake8 lint Python code
      run: flake8 src/

  yapf:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
    - run: pip install yapf toml
    - name: Yapf source formatting
      run: |
        yapf src/ --recursive -d
        yapf tests/ --recursive -d
        yapf template/ --recursive -d

  mypy:
    name: Type checking
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
    - run: pip install mypy types-toml
    - name: Mypy type checking
      run: mypy src

  bandit:
    name: Security checking
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
    - run: pip install bandit
    - name: Bandit security checking
      run: bandit -r src -ll

  misspell:
    name: Check misspellings
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
    - name: Check misspellings
      uses: codespell-project/actions-codespell@v1
      with:
        builtin: clear,rare
        check_filenames: true
        ignore_words_list: assertIn,crate,
