name: Fast checks

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
  pull_request:
# Cancel previous runs on this reference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  python_checks:
    name: Python checks
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_python_checks.yml@v1
    with:
      run_type_check: true
      run_security_check: true
      src_directory: "src"
      bandit_severity_level: "medium"

  mispell:
    name: Check misspellings
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_spell_check.yml@v1
    with:
      ignore_words_list: assertIn,crate,
